### ISSUE TITLE
Cannot decrypt device in LOS 15.1

### ISSUE THREAD

**Issue by jorti** [omnirom/android_bootable_recovery#224]
- [X] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [X] I am running the latest version of TWRP
- [X] I have read the FAQ (https://twrp.me/FAQ/)
- [X] I have searched for my issue and it does not already exist

**Device codename**: bacon
**TWRP version**: 3.2.1-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
- Wipe everything and install latest LOS 15.1 and GApps
- Encrypt device
- TWRP fails to decrypt it every time, it keeps asking for the password.

#### WHAT IS THE EXPECTED RESULT?
Decrypt the devices successfully

#### WHAT HAPPENS INSTEAD?
Cannot decrypt the data partition

#### ADDITIONAL INFORMATION
```
Updating partition details...
...done
Unable to mount storage
Full SELinux support is present.
Failed to decrypt data.
Failed to decrypt data.
```

**Comment by jorti** [comment]
The problem persists in twrp-bacon-3.2.2-0

**Comment by AnotherElk** [comment]
Exact same issue as @jorti, but on the Fairphone 2 ...

Device codename: FP2
TWRP version: 3.2.2-0

**For Screen Lock in LineageOS 15.1 set to “None”** the TWRP console (?) output reads:

```
Failed to decrypt data.
Unable to decrypt with default password. You may need to perform a Format Data.
Updating partition details...
...done
Unable to mount storage
Full SELinux support is present.
```

At this point TWRP prompts for a decryption password, but there is none. Every attempt to enter one adds the following line to the output:

`Failed to decrypt data.`

**For Screen Lock set to an actual lock** (pattern/ PIN/ password) the output reads

```
Updating partition details...
...done
Unable to mount storage
Full SELinux support is present.
```
At this point TWRP prompts for the decryption pattern/ password (TWRP doesn’t distinguish between PIN and password with this prompt, worked with PINs nonetheless in the past).
Every attempt to decrypt with the pattern/ PIN/ password given by the user adds the following line to the output:

`Failed to decrypt data.`

**recovery.log for both cases** ...

[recovery.screenlocknone.log](https://github.com/omnirom/android_bootable_recovery/files/2216475/recovery.screenlocknone.log)

[recovery.screenlock.log](https://github.com/omnirom/android_bootable_recovery/files/2216476/recovery.screenlock.log)

**Comment by T3stX** [comment]
Same issue on mido.

**Comment by tyllmoritz** [comment]
I have the same issue on mako (Nexux 4).

TWRP versions: 3.2.2-0 and 3.2.1-0

Only difference:
I installed latest "LineageOS for microG" instead of "latest LOS 15.1 and GApps"

**Comment by mopinsk** [comment]
Same on mido (Xiaomi Redmi Note 4) with TWRP 3.2.1.0 and 3.2.2.0. Can't decrypt via GUI and/or cmd.

**Comment by bluteau** [comment]
Similar issue on cheeseburger (OnePlus 5) with TWRP 3.2.3-0 and 3.2.2-0, but there is never a prompt for a PIN/password, decryption simply fails and /data cannot mount. Interestingly, 3.2.1-1 does not have this issue, and decryption works fine with LOS 15.1

**Comment by benwaffle** [comment]
I think the problem might be related to file-based encryption. Running `vold` gives:
```
/data/system # vold
CANNOT LINK EXECUTABLE "vold": cannot locate symbol "_ZN7android4base14DefaultAborterEPKc" referenced by "/system/bin/vold"...
libc: CANNOT LINK EXECUTABLE "vold": cannot locate symbol "_ZN7android4base14DefaultAborterEPKc" referenced by "/system/bin/vold"...
libc: Fatal signal 6 (SIGABRT), code -6 in tid 3159 (vold), pid 3159 (vold)
```

**Comment by roukydesbois** [comment]
With the same device (FP2) than @AnotherElk I have the same behaviour with TWRP 3.2.3-0, 3.2.1-0 and 3.1.1-2

**Comment by Poutcle** [comment]
J'ai le même problème avec mon Xiaomi note 4 globale version. Twrp 3.2.3-0 et lineage 15.1. Il met impossible d'accéder a la partition data...

**Comment by ebcBIOHAZARD** [comment]
I have the same problem with twrp 3.2.3.0 and LineageOS 15.1 (Build 20181022) on my Fairphone 2.

Decryption at LOS-Boot works, in twrp 3.2.3.0 not. The error-message is:

Updating partition details…
…done
Unable to mount storage
Full SELinux support is present.
Failed to decrypt data.

Im sure, ive typed the correct code, the key works by starting into LOS.
Any updates or further informations..?

Greez ebcBIOHAZARD

**Comment by geronimoge** [comment]
I've got the same problem using a Samsung Galaxy S9 (starlte).

**Comment by tbdal** [comment]
i'm having the same issue on a fairphone2 with twrp-3.2.3-0-FP2.img & lineage-15.1-20181120-nightly-FP2-signed.
it was working before though if i remember correctly.
any ideas?

@mopinsk: was that issue resolved since 3.2.3-1 or 3.2.3-0 ?

**Comment by giner** [comment]
It was resolved in 3.2.3-1. Works for me on mido also now.

**Comment by giner** [comment]
BTW, 3.2.3-0 is unable mount internal disk even if it's not encrypted. 3.2.3-1 works perfect.

**Comment by kumajaya** [comment]
Fix available:
1. https://review.lineageos.org/q/topic:%22bacon-twrp%22
2. https://github.com/kumajaya/android_bootable_recovery/commits/lineage-15.1

TWRP binary: https://drive.google.com/file/d/1IWH9vRHsjKRy4v2PxwwZNk8cr1xTIiqD/view?usp=sharing

You have to flash it for working decryption.

**Comment by tbdal** [comment]
> Fix available:
> 
>     1. https://review.lineageos.org/q/topic:%22bacon-twrp%22
> 
>     2. https://github.com/kumajaya/android_bootable_recovery/commits/lineage-15.1
> 
> 
> TWRP binary: https://goo.gl/iVRPW8
> 
> You have to flash it for working decryption.

this patch can only be applied for the device bacon, correct? 
may this be adapted to work with other devices, too?
i'd love to see finally a solution on this. LOS15.1 is practically not encryptable on the fairphone 2 and many other devices :(

**Comment by agherzan** [comment]
Same issue on cheeseburger. Any updates on a fix here?

**Comment by OniriCorpe** [comment]
Always same issue on FP2 with the latest TWRP release (3.3.0-0).

**Comment by jjerphan** [comment]
I still have the problem on OnePlus One encrypted with LineageOS 15.1, with the latest TWRP release (3.3.0-0).

**Comment by HorlogeSkynet** [comment]
Well I'm going to post quite the opposite of the above message 'cause : Decryption succeeded with the latest TWRP release (3.3.1-0) :tada:

Device : Bacon, with a `data` partition encrypted by ResurrectionRemix 6.0 (based on LineageOS 15.1).

Bye :wave:

**Comment by jorti** [comment]
For me it's fixed on 3.3.1 on LOS 16.0

**Comment by jjerphan** [comment]
It also now works for me with TWRP 3.3.1 on LineAgeOS 16.0.

Thanks!

**Comment by madox85** [comment]
For me it does NOT work. TWRP-3.3.1.0 on starlte with LOS 15.1

**Comment by vbrandl** [comment]
The problem still exists on a Oneplus One with LineageOS 16.0 and TWRP 3.3.1-0

Strangely, I use a PIN to decrypt the device but TWRP asks for a password. Changing the PIN to a password doesn't change anything and when rebooting the device, android still asks for the old PIN instead of the password...

**Comment by kolAflash** [comment]
Problem also still exists on FP2 (Fairphone 2), using TWRP-3.3.1-1 and LineageOS-16.0 (2019-12-12-nightly).

```
I:Command 'decrypt 123456789' received
I:Set page: 'singleaction_page'
I:operation_start: 'TWRP CLI Command'
Attempting to decrypt data partition via command line.
D:crypt_ftr->fs_size = 54386623
I:Using scrypt with keymaster for cryptfs KDF
overlay_display_frame failed, overlay play Failed
: Operation not permitted
-1, 3, 3, 1
I:TWRP keymaster max API: 1
I:Signing safely-padded objectkeymaster module name is Keymaster QCOM HAL
keymaster version is 3
Found keymaster0 module, using keymaster0 API.
E:Keymaster signing failedE:kdf failedW:failure decrypting master keyE:Failed to decrypt master key
E:Password did not matchFailed to decrypt data.
```
